### PR TITLE
Add Visualizing Weights article links & citations

### PR DESCRIPTION
**Pull request by ProGamerGov**

### CODE REVIEW

**Comment by csvoss** [comment]
This looks great to me. Thanks for grabbing one of these!

Apologies for the delay on my end here – I'm catching up on a batch of tasks I made for myself when catching up on Slack recently :)

I could merge it but I'd prefer to defer to @colah to push the button on it for _Zoom In_ – Chris, if it saves you time, consider this pull request to be reviewed & approved by at least me :)

**Comment by colah** [comment]
Sorry for not seeing this earlier. I like adding the link, and I'm generally excited to incorporate links to this article through out. At some point, I'd actually love to slightly tweak the text of this article to make it more explicitly call out future articles in the thread.

Some nit picks, since I'm a bit obsessed with this article:

I think adding a forward self-citation feels a bit weird and like something that there's a tiny risk it could be perceived as citation hacking. We haven't done this for other articles. I'd personally just add the link.

I'm also not sure it's natural to cite for "you can read algorithms off the weights" (eg. this article and curve circuits are giving a lot more evidence that's possible).

**Comment by ProGamerGov** [comment]
@colah Okay, I've removed the first the link to the article and I also removed the citation to avoid the risk of citation hacking!

**Comment by colah** [comment]
Looks great, thanks so much for the PR!

**Pull request merged**
